services:
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: cars_db
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://root:password@mongo:27017/cars_db?authSource=admin

volumes:
  mongo-data: